---
refresh_interval: 300 # seconds
urls:
  - https://store.ui.com/collections/unifi-network-switching/products/usp-rps
  - https://store.ui.com/collections/unifi-network-wireless/products/access-point-wifi-6-in-wall
  - https://store.ui.com/collections/unifi-protect/products/uvc-g4-bullet
...